### ISSUE TITLE
The coordinates system used in the blender_dataset

### ISSUE THREAD

**Issue by yilinliu77** [yunfan1202/NEF_code#1]
Thanks for sharing the code!

I have a question about the released dataset. The code in `datasets/blender.py`, line `46-48`, shows that the transformation is defined as `camera to world` manner. However, when I take a 3D point on the obj file, let's say point `(-2.58, -6.47, -3.81)` in the mesh `00000077_767e4372b5f94a88a7a17d90_trimesh_018.obj`, and multiply it using `camera_intrinsics @ inv(transform_matrix) @ point`. I cannot get the right pixel position of this point on the image. Do I miss something?

**Comment by yunfan1202** [comment]
If I understand correctly, you want to project a 3D object into 2D images with given poses.

I rendered the dataset through the project BlenderProc (https://github.com/DLR-RM/BlenderProc). If you want to create a customized dataset, I suggest using off-the-shelf tools if needed.

**Comment by yilinliu77** [comment]
Thanks for your quick reply! Yes, I want to project the 3D object into 2D images. Just like the extrinsic and intrinsic matrix provided by COLMAP. But I cannot get the right position using the projection matrix in the JSON.

What is the meaning of the `transform_matrix` in the JSON? I assume it is the matrix that converts the point from the camera coordinate to the world coordinate. Is there any other transformation involved? I read the code in `llff.py`. It seems that some other transformations such as `center_poses` also related to the composition of the matrix. Is that the problem?

**Comment by yilinliu77** [comment]
It turns out that the obj file has some additional translation and scaling before the rendering. Here I leave the instructions for how I project the point of the object to the image.

- The object should be centred at `(0.5,0.5,0.5)` and scale by the length of the largest axis. So any point of the object will be in `[0,1]`.
- The `transform_matrix` is the matrix from the camera coordinate to the world coordinate. So if we want to transform a world point to the image plane, we should inverse it.
- Before multiplying the intrinsic matrix, we should additionally invert the `x-axis`.

**Comment by wtupdl** [comment]
Hello, can you provide the code for rendering images using blenderproc?

**Comment by C-H-Chien** [comment]
> It turns out that the obj file has some additional translation and scaling before the rendering. Here I leave the instructions for how I project the point of the object to the image.
> 
>     * The object should be centred at `(0.5,0.5,0.5)` and scale by the length of the largest axis. So any point of the object will be in `[0,1]`.
> 
>     * The `transform_matrix` is the matrix from the camera coordinate to the world coordinate. So if we want to transform a world point to the image plane, we should inverse it.
> 
>     * Before multiplying the intrinsic matrix, we should additionally invert the `x-axis`.

Thanks for the informative and helpful instructions.
I am trying to do the same thing by projecting the curves to the images.
I wonder:
1. What does it mean when you say "The object should be centred at `(0.5,0.5,0.5)`"? Does it mean that the average position of all curve points should be shifted to `(0.5,0.5,0.5)`?
2. What does it mean by "scale by the length of the largest axis"?

**Comment by yilinliu77** [comment]
1. Before applying the transformation matrix, the centre of the object's bounding box should be placed at (0.5,0.5,0.5).
2. Then each axis should be divided by the length of the largest side of the bounding box, in order to scale the whole object to [0,1]
