### ISSUE TITLE
GT curve points do not make sense for some of the objects in the ABC-NEF dataset

### ISSUE THREAD

**Issue by C-H-Chien** [yunfan1202/NEF_code#10]
Hi! When showing ground-truth curve points for some objects in the ABC-NEF dataset, they seem to be incorrect. For example, the GT curve points of object 2524 from your code is:
![Screenshot from 2024-11-16 18-40-08](https://github.com/user-attachments/assets/d34122b3-0f8b-4b42-b50b-d4753257277d)
while if I plot if on my own, it makes much more sense:
![Screenshot from 2024-11-16 18-30-43](https://github.com/user-attachments/assets/f9f4f3e4-5e3c-49ea-9bca-02bae8ff9c4f)
Similar issue has been observed for object 9779.
Any thoughts?

**Comment by yunfan1202** [comment]
There is an attribute named "sharp" in each corresponding ".yml" file. Compared to the ABC-NEF dataset, which only considered sharp curves, you just visualized all "sharp: false" curves.
For example:
[00002524_4cda48e8579349d6a4becfbf_features_014.zip](https://github.com/user-attachments/files/17789082/00002524_4cda48e8579349d6a4becfbf_features_014.zip)

**Comment by C-H-Chien** [comment]
I see. May I ask why non-sharp curves are not used for GT? Do "sharp" curves originate from the original ABC dataset, or are they specifically defined in the ABC-NEF dataset? Sorry for the silly question.

**Comment by yunfan1202** [comment]
The  "sharp" attribute is defined in the original ABC dataset. You can find more details in the original [ABC dataset paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Koch_ABC_A_Big_CAD_Model_Dataset_for_Geometric_Deep_Learning_CVPR_2019_paper.pdf)

In my understanding, a "sharp" edge means the normal near this point changes very sharply, which is the main target of NEF. Therefore, here non-sharp curves are not used for GTs.

**Comment by C-H-Chien** [comment]
Thank you. I appreciate your time in answering my question :)
