### ISSUE TITLE
edge detection

### ISSUE THREAD

**Issue by ZhouCX117** [yunfan1202/NEF_code#2]
Hi, I read your papers about edge detection, i.e. "STedge" and "Delving into Crispness". Do you have a plan to release the related code? I can't find your email address, so I pull an issue here. Looking forward to your answer!

**Comment by yunfan1202** [comment]
Thanks for your interest! I will release the code for "Delving into Crispness" as soon as possible (in one month) and the code for STEdge after acceptance.

**Comment by yunfan1202** [comment]
I have just released the code for "Delving into Crispness", and updated my email address on the GitHub page.
Please feel free to contact me with any problems or potential discussions.
