### ISSUE TITLE
Hello, can you provide the code for rendering images using blenderproc?

### ISSUE THREAD

**Issue by wtupdl** [yunfan1202/NEF_code#3]
Hello, can you provide the code for rendering images using blenderproc?

**Comment by yunfan1202** [comment]
Sure, if needed, I can release the rendering code based on Blenderproc after some time for cleaning. 
I recommend you try Blenderproc first, it is not our main contribution so I do not release the code the first time.

**Comment by wtupdl** [comment]
Thank you, I use blenderproc and the parameters of the json file you provided to render the obj model, but the rendered image is not the same as yours, I don't know why, so I hope you can provide a simple blenderproc rendering that you use script

**Comment by wtupdl** [comment]
mport blenderproc as bproc
import numpy as np
bproc.init()
model_path='mesh_scaled.obj'
obj = bproc.loader.load_obj(model_path)
#obj = bproc.object.create_primitive("MONKEY")
transform_matrix = np.array([
        [0.7041518092155457,0.12652449309825897,-0.6986858248710632,-2.685070037841797],
        [-0.7100494503974915,0.12547370791435242,-0.6928825378417969,-2.6586151123046875],
        [8.546974328282886e-08,0.9839958548545837,0.1781911998987198,1.3123130798339844],
        [0.0,0.0,0.0,1.0]
    ])
camera_intrinsics=np.array([
        [1111.1113654242622,0.0,399.5],
        [0.0,1111.1113654242622,399.5],
        [0.0,0.0,1.0]
    ])
light1 = bproc.types.Light()
light1.set_location([2, 2, 2])
light1.set_energy(500)
light2 = bproc.types.Light()
light2.set_location([-2, -2, 3])
light2.set_energy(500)
light3 = bproc.types.Light()
light3.set_location([-2, 2, 3])
light3.set_energy(500)
bproc.camera.add_camera_pose(transform_matrix)
bproc.camera.set_intrinsics_from_K_matrix(camera_intrinsics,800,800)

data = bproc.renderer.render()

bproc.writer.write_hdf5("output/", data)

**Comment by wtupdl** [comment]
this is my code

**Comment by yunfan1202** [comment]
transform_matrix is calculated by blender after setting the positions of the object and cameras, instead of setting the transform_matrix first in rendering scripts.
Can you provide an email address so I can send you the unorganized Blenderproc project if you are in a hurry?

**Comment by wtupdl** [comment]
OK, thank you, my email address is wtupdl@163.com

**Comment by eunzihong** [comment]
Hi, Yunfan.

Thank you for your great work!
Can I get the BlenderProc script as well?

This is my email. `eunji.hong@kaist.ac.kr` 
Thank you in advance.

**Comment by yunfan1202** [comment]
The entire BlenderProc project used in this work can be downloaded [Here](https://drive.google.com/file/d/155rPkcJyBGRnyrG4Fu5mLAcTWCFTM8Ue/view). For more details about the ABC dataset, see BlenderProc_NEF/examples/datasets/abc_dataset/main.py for references.
