### ISSUE TITLE
"Transforms_test.json" missing

### ISSUE THREAD

**Issue by yiboz2001** [yunfan1202/NEF_code#5]
Hello! When I try the command of "Novel View Synthesis", it seems like the "transforms_test.json" file missing. Could you please advise me on how to find or create it?

**Comment by yiboz2001** [comment]
To render a 360-degree video for the NeRF result and set the azimuth degree to 0.

**Comment by yunfan1202** [comment]
The “transforms_\**.json” file provides pose parameters in a format like the "nerf_synthetic" dataset. You can change the default "args.split" to "train" or "val" or "video" (Updated).
In this project, “transforms_**.json”files are generated by the modification of BlenderProc: https://github.com/DLR-RM/BlenderProc, which can be found at https://drive.google.com/file/d/155rPkcJyBGRnyrG4Fu5mLAcTWCFTM8Ue/view
