### ISSUE TITLE
Questions on evaluations

### ISSUE THREAD

**Issue by C-H-Chien** [yunfan1202/NEF_code#6]
First of all, thanks for the amazing work! I have a few questions on how the 3D edges are evaluated:

1. When sampling points on the parametric curves, the paper says that the points are down-sampled on voxel grids. What is the size of the voxel grids you use? 
2. In Table 1 of the paper, is the numbers for IoU, precision, recall, etc the average of all objects in the A-N and A-N-L datasets?
3. In Figure 2 of the supplementary materials, how do you choose the views? The supp says "all evenly distributed" but it is based on what criteria, i.e., the baseline of cameras? The order of the images in the dataset is not in the order of how the camera moves.

Thanks!

**Comment by yunfan1202** [comment]
Thanks a lot for your appreciation!
1. See [visualize_and_eval_NEF.py](https://github.com/yunfan1202/NEF_code/blob/main/parametric_curve/visualize_and_eval_NEF.py) for more details. As shown in line 42, the size of the voxel grids is set to 64.
2. Exactly, the final value of IoU, precision, recall, etc, is calculated as the average. 
3. In the main paper, section 4.1-ABC-NEF Dataset: "views are sampled by evenly placing cameras on a sphere by Fibonacci sampling [12]".
For more coding details, the entire BlenderProc project used in this work can be downloaded [Here](https://drive.google.com/file/d/155rPkcJyBGRnyrG4Fu5mLAcTWCFTM8Ue/view),

**Comment by C-H-Chien** [comment]
Thank you so much for the quick reply!
