### ISSUE TITLE
Request on the ckpts of all ABC-NEF objects

### ISSUE THREAD

**Issue by C-H-Chien** [yunfan1202/NEF_code#7]
Thanks for the amazing work!
My understanding to the code is that we need to train for each object individually, _i.e._, the trained model on one object basically does not generalize to another object.
However, training the model on one object requires many hours to complete (> 6 hrs on my side), and there are over 100 objects.
Would it be possible if you could share all the ckpts of all objects so that I can quickly look into the details of the reconstruction across different objects?
Thank you!

**Comment by yunfan1202** [comment]
The pre-trained models and results are available at [Baidu Disk](https://pan.baidu.com/s/12h0y9n2d76FUJoP4Dt6ZVw?pwd=mcmm) or [Google Drive](https://drive.google.com/drive/folders/1b8lvF7H_fq9kNydQc5uCbDiv0qMdTIOb?usp=share_link).

**Comment by C-H-Chien** [comment]
Thank you! I am sorry it's my bad that I did not notice it earlier. Closing this thread.
